### ISSUE TITLE
taxonomies tag/categories sort out

### ISSUE THREAD

**Issue by clux** [clux/probes.hugo#4]
Was expecting to have the 6 main things from `_index` as categories, and the rest as more-specific-tags. May be very simple to do. Just putting it down to remember.

Maybe something like:

```toml
[taxonomies]
tags = ["rust", "kubernetes", "speedrun", "theorycraft"]
categories = ["cloud", "music", "gaming", "roleplay"]
```
